credit_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('YHP_DUCKDB_PATH', 'credit.duckdb')}}"
      threads: 4
      extensions:
        - sqlite
      attach:
        - path: "{{ env_var('YHP_SQLITE_PATH', '../data/YHP_credit_assessment_DS.sqlite') }}"
          type: sqlite
          alias: raw
          read_only: true
